#
# Copyright (C) 2011-2021 Intel Corporation. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#   * Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#   * Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#   * Neither the name of Intel Corporation nor the names of its
#     contributors may be used to endorse or promote products derived
#     from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#

include buildenv.mk

define DIR_EXISTS
$(shell test -d $(1) && echo "$(1)")
endef

SGX_SDK := /tmp/intel/sgxsdk
export SGX_SDK

.PHONY: build psw dcap install clean sdk install_sdk ippcp

build: psw dcap

psw: install_sdk
	@$(MAKE) -C psw/urts/linux/ USE_OPT_LIBS=$(USE_OPT_LIBS)

dcap: install_sdk
	# Workaround until fixed in DCAP: prebuild race-prone targets, then skip
	# re-entering them in the full DCAP build; build only RPM PcsClientTool.
	@$(MAKE) -C external/dcap_source/external
	@$(MAKE) -j1 -C external/dcap_source/ QuoteVerification
	@$(MAKE) -j1 -C external/dcap_source/ PCKCertSelection
	# The default PckClientTool target also builds DEB packages and needs dpkg.
	@$(MAKE) -C external/dcap_source/tools/PcsClientTool rpm_sgx_pcs_client_pkg
	# WinPle targets build Windows PLE artifacts, not Linux RPM content. 
	#  Note: if wanting to build them, and using OpenSSL 3x CLI, make sure to use --traditional for PLE signing key generation
	@$(MAKE) -C external/dcap_source/ -o ThirdParty -o QuoteVerification -o PCKCertSelection -o PckClientTool -o WinPle -o WinPleIntel


install:
	@$(MAKE) -I linux/installer/common/psw-tdx -f linux/installer/common/psw-tdx/Makefile SRCDIR=. DESTDIR=$(DESTDIR) install

clean:
	@$(MAKE) -C psw/urts/linux/       clean
	@$(MAKE) -C external/dcap_source/ clean
	@$(MAKE) -C sdk/                  clean
	@$(MAKE) -C external/ippcp_internal/ clean
ifneq ($(call DIR_EXISTS,$(SGX_SDK)),)
	$(SGX_SDK)/uninstall.sh
endif

ippcp:
	$(MAKE) -C external/ippcp_internal/
sdk: ippcp
	$(MAKE) -C sdk/

install_sdk: sdk
	./linux/installer/bin/build-installpkg.sh sdk
ifeq ($(call DIR_EXISTS,$(SGX_SDK)),)
	./linux/installer/bin/sgx_linux_x64_sdk_*.bin --prefix=$(dir $(SGX_SDK))
endif
